project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ./slides/presentation.qmd


format:
  html:
    theme: cosmo
    toc: true



